#!/usr/bin/env node
/**
 * generate.js
 * Regenerates projects/manifest.json and sitemap.xml from the contents of
 * the projects/ directory, so neither file ever has to be edited by hand.
 *
 *   node scripts/generate.js      (or: npm run generate)
 *
 * - manifest.json: every projects/<slug>/ folder that contains a
 *   project.json. The existing manifest order is preserved; new projects
 *   are appended at the end (move slugs around in manifest.json afterwards
 *   if you want a different display order - the order is kept on re-runs).
 * - sitemap.xml: the static root pages plus every project that declares a
 *   "viewPage". lastmod comes from the last git commit that touched the
 *   file (today's date for files with uncommitted changes).
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const PROJECTS_DIR = path.join(ROOT, 'projects');
const MANIFEST_PATH = path.join(PROJECTS_DIR, 'manifest.json');
const SITEMAP_PATH = path.join(ROOT, 'sitemap.xml');
const SITE = 'https://matthewderekrall.com';

// Static root pages: [path, changefreq, priority]
const STATIC_PAGES = [
    ['/',                  'monthly', '1.0', 'index.html'],
    ['/work.html',         'monthly', '0.9', 'work.html'],
    ['/about.html',        'monthly', '0.8', 'about.html'],
    ['/research.html',     'yearly',  '0.7', 'research.html'],
    ['/achievements.html', 'monthly', '0.7', 'achievements.html'],
    ['/contact.html',      'yearly',  '0.6', 'contact.html'],
];

function today() {
    return new Date().toISOString().slice(0, 10);
}

/** lastmod for a repo-relative file: last git commit date, or today if the
 *  file is new/modified since the last commit (or git is unavailable). */
function lastmod(relFile) {
    try {
        const dirty = execSync('git status --porcelain -- "' + relFile + '"', {
            cwd: ROOT, encoding: 'utf8',
        }).trim();
        if (dirty) return today();
        const date = execSync('git log -1 --format=%cs -- "' + relFile + '"', {
            cwd: ROOT, encoding: 'utf8',
        }).trim();
        return date || today();
    } catch (e) {
        return today();
    }
}

function generateManifest() {
    const dirs = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true })
        .filter(function (d) { return d.isDirectory(); })
        .map(function (d) { return d.name; })
        .filter(function (name) {
            return fs.existsSync(path.join(PROJECTS_DIR, name, 'project.json'));
        });

    let existing = [];
    try {
        existing = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
    } catch (e) { /* no manifest yet - start fresh */ }

    // Keep the existing order for slugs that still exist, append new ones.
    const kept = existing.filter(function (slug) { return dirs.indexOf(slug) !== -1; });
    const added = dirs.filter(function (slug) { return kept.indexOf(slug) === -1; }).sort();
    const manifest = kept.concat(added);

    fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');

    const removed = existing.filter(function (slug) { return dirs.indexOf(slug) === -1; });
    console.log('manifest.json: ' + manifest.length + ' projects' +
        (added.length ? ' (+' + added.join(', +') + ')' : '') +
        (removed.length ? ' (-' + removed.join(', -') + ')' : ''));
    return manifest;
}

function urlEntry(loc, mod, freq, priority) {
    return '  <url>\n' +
        '    <loc>' + loc + '</loc>\n' +
        '    <lastmod>' + mod + '</lastmod>\n' +
        '    <changefreq>' + freq + '</changefreq>\n' +
        '    <priority>' + priority + '</priority>\n' +
        '  </url>\n';
}

function generateSitemap(manifest) {
    let xml = '<?xml version="1.0" encoding="UTF-8"?>\n' +
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n\n' +
        '  <!-- Generated by scripts/generate.js - do not edit by hand -->\n\n';

    STATIC_PAGES.forEach(function (p) {
        xml += urlEntry(SITE + p[0], lastmod(p[3]), p[1], p[2]);
    });

    xml += '\n  <!-- PROJECT VIEW PAGES -->\n';
    let viewCount = 0;
    manifest.forEach(function (slug) {
        let proj;
        try {
            proj = JSON.parse(fs.readFileSync(path.join(PROJECTS_DIR, slug, 'project.json'), 'utf8'));
        } catch (e) { return; }
        if (!proj.viewPage) return;
        const rel = String(proj.viewPage).replace(/^\//, '');
        xml += urlEntry(SITE + '/' + rel, lastmod(rel), 'monthly', '0.6');
        viewCount++;
    });

    xml += '\n</urlset>\n';
    fs.writeFileSync(SITEMAP_PATH, xml);
    console.log('sitemap.xml: ' + STATIC_PAGES.length + ' static pages + ' + viewCount + ' view pages');
}

const manifest = generateManifest();
generateSitemap(manifest);
